GET http://localhost:3000/api/articles/ HTTP/1.1
###

GET http://localhost:3000/api/articles/OUlGww HTTP/1.1
###

GET http://localhost:3000/api/categories/ HTTP/1.1
###

POST http://localhost:3000/api/articles/ HTTP/1.1
Content-Type: application/json

{
    "title": "Ёлки. История деревьев",
    "createdDate": "5/4/2020, 10:20:00",
    "announce": ["Он написал больше 30 хитов."],
    "fullText": [
      "Первая большая ёлка была установлена только в 1938 году.",
      "Это один из лучших рок-музыкантов.",
      "Игры и программирование разные вещи. Не стоит идти в программисты, если вам нравится только игры.",
      "Процессор заслуживает особого внимания. Он обязательно понравится геймерам со стажем.",
      "Альбом стал настоящим открытием года. Мощные гитарные рифы и скоростные соло-партии не дадут заскучать.",
      "Рок-музыка всегда ассоциировалась с протестами. Так ли это на самом деле?"
    ],
    "category": ["Разное", "Программирование"]
  }
###

PUT http://localhost:3000/api/articles/OUlGww HTTP/1.1
Content-Type: application/json

{
    "title": "Рок — это протест 👍",
    "createdDate": "3/11/2020, 06:42:14",
    "announce": [
      "Помните, небольшое количество ежедневных упражнений лучше, чем один раз, но много.",
      "Это один из лучших рок-музыкантов.",
      "Бороться с прокрастинацией несложно. Просто действуйте. Маленькими шагами."
    ],
    "fullText": [
      "Это один из лучших рок-музыкантов.",
      "Простые ежедневные упражнения помогут достичь успеха.",
      "Бороться с прокрастинацией несложно. Просто действуйте. Маленькими шагами.",
      "Освоить вёрстку несложно. Возьмите книгу новую книгу и закрепите все упражнения на практике.",
      "Собрать камни бесконечности легко, если вы прирожденный герой."
    ],
    "category": [
      "Программирование"
    ],
    "comments": [
      {
        "id": "_Cagtp",
        "text": "Плюсую, но слишком много букв! Давно не пользуюсь стационарными компьютерами. Ноутбуки победили. Планируете записать видосик на эту тему?"
      },
      {
        "id": "UwJGiK",
        "text": "Совсем немного... Хочу такую же футболку :-)"
      }
    ]
  }
###

DELETE http://localhost:3000/api/articles/OUlGww HTTP/1.1
###

GET http://localhost:3000/api/articles/c1w4dl/comments HTTP/1.1
###

DELETE http://localhost:3000/api/articles/c1w4dl/comments/CnFvpB HTTP/1.1
###

POST http://localhost:3000/api/articles/c1w4dl/comments/ HTTP/1.1
Content-Type: application/json

{
  "text": "🔥"
}
###

GET http://localhost:3000/api/search?query=Рок HTTP/1.1
###
